
---
/**:
  ros__parameters:
    number_of_sources: 2
    output_frame_id:  "base_link"
    cloud_size:       55000
    rubis:
      use_timer: true
      sched_info:
        task_id: 1
        max_opt: 1
        name: "point_cloud_fusion"
        log_dir: "/home/rubis/rubis_log/"
        exec_time: 5000000  # 20ms
        deadline: 5000000  # 10ms
        period: 12000000  # 30ms 1000000 = 1ms
        # exec_time: 15000000  # 15ms
        # deadline: 25000000  # 20ms
        # period: 25000000  # 20ms
