# Copyright 2020 RUBIS
---

/**:
  ros__parameters:
    target_vel: 10.0
    cur2tar: 1.0
    safe_dist: 30.0
    danger_scale: 20
    rubis:
      sched_info:
        task_id: 1
        max_opt: 4
        name: "rubis_drive"
        log_dir: "/home/rubis/rubis_log/"
        exec_time: 100000000  # 0.1s
        deadline: 200000000  # 0.2s
        period: 300000000  # 0.3s
