# Copyright 2020 RUBIS

/**:
  ros__parameters:
    target_vel: 10.0
    cur2tar: 1.3
    safe_dist0: 10.0
    safe_dist1: 20.0
    safe_dist2: 30.0
    danger_scale: 8.0
    lookahead: 800
    rubis:
      sched_info:
        task_id: 1
        max_opt: 3
        name: "rubis_drive"
        log_dir: "/home/rubis/rubis_log/"
        exec_time: 9000000  # 10ms
        deadline: 16000000  # 30ms
        period: 20000000  # 30ms

#exec_base = 7000000