# config/test.param.yaml
---
lidar_0:
  filter_transform_vlp16_front:
    ros__parameters:
      timeout_ms:       110
      pcl_size:         55000
      input_frame_id:  "lidar_0"
      output_frame_id: "base_link"
      init_timeout_ms:  5000
      expected_num_subscribers: 1
      expected_num_publishers:  1
      start_angle:            0       # radians
      end_angle:              6.28
      min_radius:             6.0      # meters
      max_radius:             150.0
      static_transformer:
        quaternion:
          x:                    0.0
          y:                    0.0
          z:                    0.0
          w:                    1.0
        translation:
          x:                    1.498
          y:                    -0.022
          z:                    1.49
      rubis:
        sched_info:
          task_id: 7
          name: "point_cloud_filter_transform_0"
          log_dir: "/home/rubis/rubis_log/"
          exec_time: 10.0
          period: 20.0
          deadline: 30.0

lidar_2:
  filter_transform_vlp16_front:
    ros__parameters:
      timeout_ms:       110
      pcl_size:         55000
      input_frame_id:  "lidar_2"
      output_frame_id: "base_link"
      init_timeout_ms:  5000
      expected_num_subscribers: 1
      expected_num_publishers:  1
      start_angle:            0       # radians
      end_angle:              6.28
      min_radius:             6.0      # meters
      max_radius:             150.0
      static_transformer:
        quaternion:
          x:                    0.0
          y:                    0.0
          z:                    0.0
          w:                    1.0
        translation:
          x:                    1.498
          y:                    -0.022
          z:                    1.49
      rubis:
        sched_info:
          task_id: 7
          name: "point_cloud_filter_transform_2"
          log_dir: "/home/rubis/rubis_log/"
          exec_time: 10.0
          period: 20.0
          deadline: 30.0

lidar_4:
  filter_transform_vlp16_front:
    ros__parameters:
      timeout_ms:       110
      pcl_size:         55000
      input_frame_id:  "lidar_4"
      output_frame_id: "base_link"
      init_timeout_ms:  5000
      expected_num_subscribers: 1
      expected_num_publishers:  1
      start_angle:            0       # radians
      end_angle:              6.28
      min_radius:             6.0      # meters
      max_radius:             150.0
      static_transformer:
        quaternion:
          x:                    0.0
          y:                    0.0
          z:                    0.0
          w:                    1.0
        translation:
          x:                    1.498
          y:                    -0.022
          z:                    1.49
      rubis:
        sched_info:
          task_id: 7
          name: "point_cloud_filter_transform_4"
          log_dir: "/home/rubis/rubis_log/"
          exec_time: 10.0
          period: 20.0
          deadline: 30.0

lidar_6:
  filter_transform_vlp16_front:
    ros__parameters:
      timeout_ms:       110
      pcl_size:         55000
      input_frame_id:  "lidar_6"
      output_frame_id: "base_link"
      init_timeout_ms:  5000
      expected_num_subscribers: 1
      expected_num_publishers:  1
      start_angle:            0       # radians
      end_angle:              6.28
      min_radius:             6.0      # meters
      max_radius:             150.0
      static_transformer:
        quaternion:
          x:                    0.0
          y:                    0.0
          z:                    0.0
          w:                    1.0
        translation:
          x:                    1.498
          y:                    -0.022
          z:                    1.49
      rubis:
        sched_info:
          task_id: 7
          name: "point_cloud_filter_transform_6"
          log_dir: "/home/rubis/rubis_log/"
          exec_time: 10.0
          period: 20.0
          deadline: 30.0

lidar_1:
  filter_transform_vlp16_rear:
    ros__parameters:
      timeout_ms:       110
      pcl_size:         55000
      input_frame_id:  "lidar_1"
      output_frame_id: "base_link"
      init_timeout_ms:  5000
      expected_num_subscribers: 1
      expected_num_publishers:  1
      start_angle:            0.0       # radians
      end_angle:              6.28
      min_radius:             6.0       # meters
      max_radius:             150.0
      static_transformer:
        quaternion:
          x:                    0.0
          y:                    0.0
          z:                    0.0
          w:                    1.0
        translation:
          x:                    0.308
          y:                    -0.022
          z:                    1.49
      rubis:
        sched_info:
          task_id: 7
          name: "point_cloud_filter_transform_1"
          log_dir: "/home/rubis/rubis_log/"
          exec_time: 10.0
          period: 20.0
          deadline: 30.0

lidar_3:
  filter_transform_vlp16_rear:
    ros__parameters:
      timeout_ms:       110
      pcl_size:         55000
      input_frame_id:  "lidar_3"
      output_frame_id: "base_link"
      init_timeout_ms:  5000
      expected_num_subscribers: 1
      expected_num_publishers:  1
      start_angle:            0.0       # radians
      end_angle:              6.28
      min_radius:             6.0       # meters
      max_radius:             150.0
      static_transformer:
        quaternion:
          x:                    0.0
          y:                    0.0
          z:                    0.0
          w:                    1.0
        translation:
          x:                    0.308
          y:                    -0.022
          z:                    1.49
      rubis:
        sched_info:
          task_id: 7
          name: "point_cloud_filter_transform_3"
          log_dir: "/home/rubis/rubis_log/"
          exec_time: 10.0
          period: 20.0
          deadline: 30.0

lidar_5:
  filter_transform_vlp16_rear:
    ros__parameters:
      timeout_ms:       110
      pcl_size:         55000
      input_frame_id:  "lidar_5"
      output_frame_id: "base_link"
      init_timeout_ms:  5000
      expected_num_subscribers: 1
      expected_num_publishers:  1
      start_angle:            0.0       # radians
      end_angle:              6.28
      min_radius:             6.0       # meters
      max_radius:             150.0
      static_transformer:
        quaternion:
          x:                    0.0
          y:                    0.0
          z:                    0.0
          w:                    1.0
        translation:
          x:                    0.308
          y:                    -0.022
          z:                    1.49
      rubis:
        sched_info:
          task_id: 7
          name: "point_cloud_filter_transform_5"
          log_dir: "/home/rubis/rubis_log/"
          exec_time: 10.0
          period: 20.0
          deadline: 30.0

lidar_7:
  filter_transform_vlp16_rear:
    ros__parameters:
      timeout_ms:       110
      pcl_size:         55000
      input_frame_id:  "lidar_7"
      output_frame_id: "base_link"
      init_timeout_ms:  5000
      expected_num_subscribers: 1
      expected_num_publishers:  1
      start_angle:            0.0       # radians
      end_angle:              6.28
      min_radius:             6.0       # meters
      max_radius:             150.0
      static_transformer:
        quaternion:
          x:                    0.0
          y:                    0.0
          z:                    0.0
          w:                    1.0
        translation:
          x:                    0.308
          y:                    -0.022
          z:                    1.49
      rubis:
        sched_info:
          task_id: 7
          name: "point_cloud_filter_transform_7"
          log_dir: "/home/rubis/rubis_log/"
          exec_time: 10.0
          period: 20.0
          deadline: 30.0       