
---
/**:
  ros__parameters:
    number_of_sources: 2
    output_frame_id:  "base_link"
    cloud_size:       55000
    rubis:
      use_timer: true
      sched_info:
        task_id: 1
        max_opt: 1
        name: "rubis_detect"
        log_dir: "/home/rubis/rubis_log/"
        exec_time: 100000000  # 0.1s
        deadline: 200000000  # 0.2s
        period: 300000000  # 0.3s
